# Generated by Django 3.2.6 on 2021-12-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('roll_number', models.CharField(default=None, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('employee', models.ManyToManyField(to='myapp.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='employe',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='clock_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='clock_out',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Breaks',
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
        migrations.DeleteModel(
            name='Leaves',
        ),
        migrations.AddField(
            model_name='break',
            name='employee',
            field=models.ManyToManyField(to='myapp.Employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ManyToManyField(to='myapp.Employee'),
        ),
    ]
